
import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'Successfully_Login': 'Successfully Login',
      'Error': 'Error',
      'Registration': 'Registration',
      'Please enter your account here': 'Please enter your account here',
      'Email or Phone number': 'Email or Phone number',
      'Enter Email or Phone number please': 'Enter Email or Phone number please',
      'Password': 'Password',
      'Enter Password please': 'Enter Password please',
      'Confirm Password': 'Confirm Password',
      'Enter Confirm Password please': 'Enter Confirm Password please',
      'Passwords do not match': 'Passwords do not match',
      'or Continue with': 'or Continue with',
      'Google': 'Google',
      "Already have an account?": "Already have an account?",
      'LOGIN': 'LOGIN',
      'Welcome Back!': 'Welcome Back!',
      'Forgot password?': 'Forgot password?',
      "Don't have an account?": "Don't have an account?",
      'SignUp': 'Sign Up',
      'Settings': 'Settings',
      'HELLO, WELCOME BACK' : 'HELLO, WELCOME BACK',
      'Email Address' : 'Email Address',
      'Enter your email' : 'Enter your email',
      'Enter your password':'Enter your password',
      'Login' : 'Login',
      'OR' : 'OR',
      'Signup' : 'Signup',
      'Email is required' : 'Email is required',
      'Enter a valid email' : 'Enter a valid email',
      "Password is required" : "Password is required",
      "Password must be at least 6 characters" : "Password must be at least 6 characters",
      'Full Name' : 'Full Name',
      'Create An Account' : 'Create An Account',
      'Get Started': 'Get Started',
      'Name is required' : 'Name is required',
      'Name must be at least 3 characters' : 'Name must be at least 3 characters',
      'Only alphabets and spaces are allowed' : 'Only alphabets and spaces are allowed',
      'Confirm Password is required' : 'Confirm Password is required',
      'Continue with Google' : 'Continue with Google',
      'HomeScreen' : 'HomeScreen',
      'Dark Mode' : 'Dark Mode',
      'Language' : 'Language',
      'Logout' : 'Logout',
    },

    'ur_PK': {
      'Successfully_Login': "کامیابی کے ساتھ لاگ ان ہوگیا۔",
      'Error': 'غلطی۔',
      'Registration': 'رجسٹریشن',
      'Please enter your account here': 'براہ کرم یہاں اپنا اکاؤنٹ درج کریں۔',
      'Email or Phone number': 'ای میل یا فون نمبر',
      'Enter Email or Phone number please': "براہ کرم ای میل یا فون نمبر درج کریں",
      'Password': "پاس ورڈ",
      'Enter Password please': "براہ کرم پاس ورڈ درج کریں",
      'Confirm Password': "پاس ورڈ کی تصدیق کریں",
      'Enter Confirm Password please': "براہ کرم تصدیق کے لیے پاس ورڈ دوبارہ درج کریں",
      'Passwords do not match': "پاس ورڈ مماثل نہیں ہیں",
      'or Continue with': "یا جاری رکھیں ساتھ",
      'Google': "گوگل",
      "Already have an account?": "کیا آپ کے پاس پہلے سے ایک اکاؤنٹ ہے؟",
      'LOGIN': "لاگ اِن",
      'Welcome Back!': "خوش آمدید دوبارہ!",
      'Forgot password?': "پاس ورڈ بھول گئے؟",
      "Don't have an account?": "کیا آپ کا اکاؤنٹ نہیں ہے؟",
      'SignUp': "سائن اپ کریں",
      'Settings': "ترتیبات",
      'HELLO, WELCOME BACK': 'ہیلو، خوش آمدید دوبارہ',
      'Email Address': 'ای میل پتہ',
      'Enter your email' : 'اپنا ای میل درج کریں',
      'Enter your password' :   'اپنا پاس ورڈ درج کریں',
      'Login' : 'لاگ اِن',
      'OR' : 'یا',
      'Signup' : 'سائن اَپ',
      'Email is required' : 'ای میل ضروری ہے',
      'Enter a valid email' : 'درست ای میل درج کریں',
      "Password is required" : 'پاس ورڈ ضروری ہے',
      "Password must be at least 6 characters" : 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے',
      'Full Name' : 'پورا نام',
      'Create An Account' : 'نیا اکاؤنٹ بنائیں',
      'Get Started' : 'شروع کریں',
      'Name is required' : 'نام ضروری ہے',
      'Name must be at least 3 characters' : 'نام کم از کم 3 حروف کا ہونا چاہیے',
      'Only alphabets and spaces are allowed' : 'صرف حروف اور خالی جگہوں کی اجازت ہے',
      'Confirm Password is required' : 'تصدیقِ پاس ورڈ ضروری ہے',
      'Continue with Google' : 'گوگل کے ساتھ جاری رکھیں',
      'HomeScreen' : 'ہوم اسکرین',
      'Dark Mode' : 'ڈارک موڈ',
      'Language' : 'زبان',
      'Logout' : 'لاگ آؤٹ',
    },

    'ar_SA': {
      'Successfully_Login': 'تم تسجيل الدخول بنجاح',
      'Error': 'خطأ',
      'Registration': 'تسجيل',
      'Please enter your account here': 'الرجاء إدخال حسابك هنا',
      'Email or Phone number': 'البريد الإلكتروني أو رقم الهاتف',
      'Enter Email or Phone number please': 'يرجى إدخال البريد الإلكتروني أو رقم الهاتف',
      'Password': 'كلمة المرور',
      'Enter Password please': 'يرجى إدخال كلمة المرور',
      'Confirm Password': 'تأكيد كلمة المرور',
      'Enter Confirm Password please': 'يرجى تأكيد كلمة المرور',
      'Passwords do not match': 'كلمات المرور غير متطابقة',
      'or Continue with': 'أو المتابعة باستخدام',
      'Google': 'جوجل',
      "Already have an account?": "هل لديك حساب؟",
      'LOGIN': 'تسجيل الدخول',
      'Welcome Back!': 'مرحباً بعودتك!',
      'Forgot password?': 'هل نسيت كلمة المرور؟',
      "Don't have an account?": "ليس لديك حساب؟",
      'SignUp': 'إنشاء حساب',
      'Settings': 'الإعدادات',
      'HELLO, WELCOME BACK': 'مرحباً، أهلاً بعودتك',
      'Email Address' :  'أدخل بريدك الإلكتروني',
      'Enter your email' : 'عنوان البريد الإلكتروني' ,
      'Enter your password' : 'أدخل كلمة المرور الخاصة بك',
      'Login' : 'تسجيل الدخول',
      'OR' : 'أو',
      'Signup' : 'إنشاء حساب',
      'Email is required' : 'البريد الإلكتروني مطلوب',
      'Enter a valid email' : 'أدخل بريداً إلكترونياً صالحاً',
      "Password is required" : 'كلمة المرور مطلوبة',
      "Password must be at least 6 characters" : 'يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل',
      'Full Name' : 'الاسم الكامل',
      'Create An Account' : 'أنشئ حساباً',
      'Get Started' : 'ابدأ',
      'Name is required' : 'الاسم مطلوب',
      'Name must be at least 3 characters' : 'يجب أن يكون الاسم مكوناً من 3 أحرف على الأقل',
      'Only alphabets and spaces are allowed' : 'يُسمح فقط بالأحرف والمسافات',
      'Confirm Password is required' : 'تأكيد كلمة المرور مطلوب',
      'Continue with Google' : 'المتابعة باستخدام جوجل',
      'HomeScreen' : 'الشاشة الرئيسية',
      'Dark Mode' : 'الوضع الداكن',
      'Language' : 'اللغة',
      'Logout' : 'تسجيل الخروج',
    },
  };
}
