// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAMdzq_jshOHtYREN2SKlg-yZPJ6nVM1c',
    appId: '1:646071122609:web:fdff90dd13410811f54090',
    messagingSenderId: '646071122609',
    projectId: 'makaha-journey-410fd',
    authDomain: 'makaha-journey-410fd.firebaseapp.com',
    storageBucket: 'makaha-journey-410fd.firebasestorage.app',
    measurementId: 'G-C3XLV5HKER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChcmp60cSumoG4jFu21nl7k7z6nW5lQuk',
    appId: '1:646071122609:android:ab5b4316906d374ef54090',
    messagingSenderId: '646071122609',
    projectId: 'makaha-journey-410fd',
    storageBucket: 'makaha-journey-410fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ-S4eCL90xaTbgH-6GtoL4GElJCBxC60',
    appId: '1:646071122609:ios:d216fbf803b62621f54090',
    messagingSenderId: '646071122609',
    projectId: 'makaha-journey-410fd',
    storageBucket: 'makaha-journey-410fd.firebasestorage.app',
    iosBundleId: 'com.example.hajjUmrahJourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ-S4eCL90xaTbgH-6GtoL4GElJCBxC60',
    appId: '1:646071122609:ios:d216fbf803b62621f54090',
    messagingSenderId: '646071122609',
    projectId: 'makaha-journey-410fd',
    storageBucket: 'makaha-journey-410fd.firebasestorage.app',
    iosBundleId: 'com.example.hajjUmrahJourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAMdzq_jshOHtYREN2SKlg-yZPJ6nVM1c',
    appId: '1:646071122609:web:1fb366bd078e2a2cf54090',
    messagingSenderId: '646071122609',
    projectId: 'makaha-journey-410fd',
    authDomain: 'makaha-journey-410fd.firebaseapp.com',
    storageBucket: 'makaha-journey-410fd.firebasestorage.app',
    measurementId: 'G-052WW85NLH',
  );
}
